package br.edu.utfpr.pb.pw45s.server.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

/**
 * Data transfer object used in category API requests and responses.
 */
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(name = "CategoryDTO", description = "Category data used in API requests and responses.")
public class CategoryDTO {

    @Schema(description = "Unique identifier of the category. Generated by the server and not required when creating.",
            example = "1")
    private Long id;

    @NotNull
    @Size(min = 2, max = 50)
    @Schema(description = "Category name. Required, between 2 and 50 characters.",
            example = "Electronics", requiredMode = Schema.RequiredMode.REQUIRED,
            minLength = 2, maxLength = 50)
    private String name;
}
