package br.edu.utfpr.pb.pw45s.server.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.util.Objects;

/**
 * JPA entity that represents a product category.
 */
@Entity
@Table(name = "tb_category")
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Getter @Setter
@Schema(name = "Category", description = "Product category persisted in the database.")
public class Category {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Unique identifier generated by the database.", example = "1",
            accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @NotNull
    @Size(min = 2, max = 50)
    @Column(length = 50, nullable = false)
    @Schema(description = "Category name. Required, between 2 and 50 characters.",
            example = "Electronics", requiredMode = Schema.RequiredMode.REQUIRED,
            minLength = 2, maxLength = 50)
    private String name;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        return Objects.equals(id, category.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
